Update task-scheduling.md
The @types/cron package does not work, it creates an error when starting the server, then I looked for the package on the npm site and it does not appear, npm brings out the @types/node-cron package, I then installed it instead of @types/cron and everything works fine!

Here is the error given by the old package (@types/cron) :

error TS2688: Cannot find type definition file for 'cron'.
The file is in the program because:
Entry point for implicit type library 'cron'

Sorry for my bad english !